//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.10 at 12:34:59 PM IST 
//


package com.ssnc.stocktransfer.model.units;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="g1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="g2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="typeprocessing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "amount",
    "g1",
    "g2",
    "typeprocessing"
})
@XmlRootElement(name = "getUnitsResponse")
public class GetUnitsResponse {

    @XmlElement(required = true, nillable = true)
    protected String amount;
    @XmlElement(required = true, nillable = true)
    protected String g1;
    @XmlElement(required = true, nillable = true)
    protected String g2;
    @XmlElement(required = true, nillable = true)
    protected String typeprocessing;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmount(String value) {
        this.amount = value;
    }

    /**
     * Gets the value of the g1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getG1() {
        return g1;
    }

    /**
     * Sets the value of the g1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setG1(String value) {
        this.g1 = value;
    }

    /**
     * Gets the value of the g2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getG2() {
        return g2;
    }

    /**
     * Sets the value of the g2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setG2(String value) {
        this.g2 = value;
    }

    /**
     * Gets the value of the typeprocessing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeprocessing() {
        return typeprocessing;
    }

    /**
     * Sets the value of the typeprocessing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeprocessing(String value) {
        this.typeprocessing = value;
    }

}
